//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodotOnFireLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnalyticEvents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyticEvents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GodotOnFireLibrary.AnalyticEvents", typeof(AnalyticEvents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earn_virtual_currency.
        /// </summary>
        public static string earn_virtual_currency {
            get {
                return ResourceManager.GetString("earn_virtual_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join_group.
        /// </summary>
        public static string join_group {
            get {
                return ResourceManager.GetString("join_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level_end.
        /// </summary>
        public static string level_end {
            get {
                return ResourceManager.GetString("level_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level_start.
        /// </summary>
        public static string level_start {
            get {
                return ResourceManager.GetString("level_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level_up.
        /// </summary>
        public static string level_up {
            get {
                return ResourceManager.GetString("level_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post_score.
        /// </summary>
        public static string post_score {
            get {
                return ResourceManager.GetString("post_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select_content.
        /// </summary>
        public static string select_content {
            get {
                return ResourceManager.GetString("select_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spend_virtual_currency.
        /// </summary>
        public static string spend_virtual_currency {
            get {
                return ResourceManager.GetString("spend_virtual_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tutorial_begin.
        /// </summary>
        public static string tutorial_begin {
            get {
                return ResourceManager.GetString("tutorial_begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tutorial_complete.
        /// </summary>
        public static string tutorial_complete {
            get {
                return ResourceManager.GetString("tutorial_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlock_achievement.
        /// </summary>
        public static string unlock_achievement {
            get {
                return ResourceManager.GetString("unlock_achievement", resourceCulture);
            }
        }
    }
}
