//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodotOnFireLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginMethods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GodotOnFireLibrary.PluginMethods", typeof(PluginMethods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseGetData.
        /// </summary>
        public static string databaseGetData {
            get {
                return ResourceManager.GetString("databaseGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseGetUserData.
        /// </summary>
        public static string databaseGetUserData {
            get {
                return ResourceManager.GetString("databaseGetUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databasePushData.
        /// </summary>
        public static string databasePushData {
            get {
                return ResourceManager.GetString("databasePushData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databasePushUserData.
        /// </summary>
        public static string databasePushUserData {
            get {
                return ResourceManager.GetString("databasePushUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseRemoveData.
        /// </summary>
        public static string databaseRemoveData {
            get {
                return ResourceManager.GetString("databaseRemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseRemoveUserData.
        /// </summary>
        public static string databaseRemoveUserData {
            get {
                return ResourceManager.GetString("databaseRemoveUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseSetData.
        /// </summary>
        public static string databaseSetData {
            get {
                return ResourceManager.GetString("databaseSetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseSetUserData.
        /// </summary>
        public static string databaseSetUserData {
            get {
                return ResourceManager.GetString("databaseSetUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseUpdateData.
        /// </summary>
        public static string databaseUpdateData {
            get {
                return ResourceManager.GetString("databaseUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databaseUpdateUserData.
        /// </summary>
        public static string databaseUpdateUserData {
            get {
                return ResourceManager.GetString("databaseUpdateUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firestoreAddData.
        /// </summary>
        public static string firestoreAddData {
            get {
                return ResourceManager.GetString("firestoreAddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firestoreDeleteData.
        /// </summary>
        public static string firestoreDeleteData {
            get {
                return ResourceManager.GetString("firestoreDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firestoreDeleteUserData.
        /// </summary>
        public static string firestoreDeleteUserData {
            get {
                return ResourceManager.GetString("firestoreDeleteUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firestoreReadData.
        /// </summary>
        public static string firestoreReadData {
            get {
                return ResourceManager.GetString("firestoreReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firestoreReadUserData.
        /// </summary>
        public static string firestoreReadUserData {
            get {
                return ResourceManager.GetString("firestoreReadUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firestoreSetData.
        /// </summary>
        public static string firestoreSetData {
            get {
                return ResourceManager.GetString("firestoreSetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firestoreSetUserData.
        /// </summary>
        public static string firestoreSetUserData {
            get {
                return ResourceManager.GetString("firestoreSetUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firestoreUpdateData.
        /// </summary>
        public static string firestoreUpdateData {
            get {
                return ResourceManager.GetString("firestoreUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firestoreUpdateUserData.
        /// </summary>
        public static string firestoreUpdateUserData {
            get {
                return ResourceManager.GetString("firestoreUpdateUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getFirebaseUser.
        /// </summary>
        public static string getFirebaseUser {
            get {
                return ResourceManager.GetString("getFirebaseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to init.
        /// </summary>
        public static string init {
            get {
                return ResourceManager.GetString("init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linkAccountWithEmail.
        /// </summary>
        public static string linkAccountWithEmail {
            get {
                return ResourceManager.GetString("linkAccountWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linkAccountWithGoogle.
        /// </summary>
        public static string linkAccountWithGoogle {
            get {
                return ResourceManager.GetString("linkAccountWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logEvent.
        /// </summary>
        public static string logEvent {
            get {
                return ResourceManager.GetString("logEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remoteConfigActivate.
        /// </summary>
        public static string remoteConfigActivate {
            get {
                return ResourceManager.GetString("remoteConfigActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remoteConfigFetch.
        /// </summary>
        public static string remoteConfigFetch {
            get {
                return ResourceManager.GetString("remoteConfigFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remoteConfigFetchAndActivate.
        /// </summary>
        public static string remoteConfigFetchAndActivate {
            get {
                return ResourceManager.GetString("remoteConfigFetchAndActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remoteConfigGetBoolean.
        /// </summary>
        public static string remoteConfigGetBoolean {
            get {
                return ResourceManager.GetString("remoteConfigGetBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remoteConfigGetDouble.
        /// </summary>
        public static string remoteConfigGetDouble {
            get {
                return ResourceManager.GetString("remoteConfigGetDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remoteConfigGetLong.
        /// </summary>
        public static string remoteConfigGetLong {
            get {
                return ResourceManager.GetString("remoteConfigGetLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remoteConfigGetString.
        /// </summary>
        public static string remoteConfigGetString {
            get {
                return ResourceManager.GetString("remoteConfigGetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendEmailVerification.
        /// </summary>
        public static string sendEmailVerification {
            get {
                return ResourceManager.GetString("sendEmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setUserProperty.
        /// </summary>
        public static string setUserProperty {
            get {
                return ResourceManager.GetString("setUserProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signInAnonymously.
        /// </summary>
        public static string signInAnonymously {
            get {
                return ResourceManager.GetString("signInAnonymously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signInGoogle.
        /// </summary>
        public static string signInGoogle {
            get {
                return ResourceManager.GetString("signInGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signInWithEmail.
        /// </summary>
        public static string signInWithEmail {
            get {
                return ResourceManager.GetString("signInWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signOut.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signUpWithEmail.
        /// </summary>
        public static string signUpWithEmail {
            get {
                return ResourceManager.GetString("signUpWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testCrash.
        /// </summary>
        public static string testCrash {
            get {
                return ResourceManager.GetString("testCrash", resourceCulture);
            }
        }
    }
}
